const baseEndpoint = '/api/v1';

export const LOOKUP_TABLES = [
  {
    key: 'categories',
    label: 'Categorias / Sectores',
    description: 'Catalogo de sectores y categorias para RFQ.',
    area: 'Operaciones y Logistica',
    appFunction: 'Define sectores y categorias de productos/servicios para RFQ.',
    endpoint: '/admin/lookups/categories',
    endpointLabel: `${baseEndpoint}/admin/lookups/categories`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'units_of_measure',
    label: 'Unidades de Medida',
    description: 'Opciones como Kg, Litros, Cajas, etc.',
    area: 'Operaciones y Logistica',
    appFunction: 'Opciones usadas al crear solicitudes y cotizaciones.',
    endpoint: '/admin/lookups/units_of_measure',
    endpointLabel: `${baseEndpoint}/admin/lookups/units_of_measure`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Abreviatura' },
      { key: 'label', label: 'Nombre' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'delivery_methods',
    label: 'Metodos de Entrega',
    description: 'Formas de despacho configurables por pais.',
    area: 'Operaciones y Logistica',
    appFunction: 'Define modalidades de despacho disponibles en transacciones.',
    endpoint: '/admin/delivery-methods',
    endpointLabel: `${baseEndpoint}/admin/delivery-methods`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'country_id', label: 'Pais' },
      { key: 'name', label: 'Metodo' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'payment_methods',
    label: 'Metodos de Pago',
    description: 'Formas de pago aceptadas por la plataforma.',
    area: 'Operaciones y Logistica',
    appFunction: 'Catalogo de medios de pago aceptados en operaciones.',
    endpoint: '/admin/lookups/payment_methods',
    endpointLabel: `${baseEndpoint}/admin/lookups/payment_methods`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'company_sizes',
    label: 'Tamanos de Empresa',
    description: 'Rangos de empleados para segmentacion.',
    area: 'Perfil de Empresa',
    appFunction: 'Segmenta empresas por rango de tamano.',
    endpoint: '/admin/lookups/company_sizes',
    endpointLabel: `${baseEndpoint}/admin/lookups/company_sizes`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'estimated_monthly_transactions',
    label: 'Volumen Transaccional',
    description: 'Rangos de facturacion estimada.',
    area: 'Perfil de Empresa',
    appFunction: 'Segmenta empresas por volumen mensual estimado.',
    endpoint: '/admin/lookups/estimated_monthly_transactions',
    endpointLabel: `${baseEndpoint}/admin/lookups/estimated_monthly_transactions`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Rango' },
      { key: 'label', label: 'Descripcion' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'verif_doc_types',
    label: 'Tipos de Documento',
    description: 'Documentos exigidos para verificacion.',
    area: 'Perfil de Empresa',
    appFunction: 'Define documentos requeridos para verificar empresas.',
    endpoint: '/admin/lookups/verif_doc_types',
    endpointLabel: `${baseEndpoint}/admin/lookups/verif_doc_types`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'cities',
    label: 'Ciudades / Municipios',
    description: 'Nivel geografico de ciudad/municipio.',
    area: 'Geografia y Moneda',
    appFunction: 'Completa nivel geografico para ubicaciones de empresa.',
    endpoint: '/admin/geography/cities',
    endpointLabel: `${baseEndpoint}/admin/geography/cities`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: false,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'state_id', label: 'Estado ID' },
      { key: 'state_name', label: 'Estado' },
      { key: 'name', label: 'Ciudad' },
    ],
  },
  {
    key: 'currencies',
    label: 'Monedas',
    description: 'Monedas activas del sistema.',
    area: 'Geografia y Moneda',
    appFunction: 'Define monedas operativas para precios y transacciones.',
    endpoint: '/admin/currencies',
    endpointLabel: `${baseEndpoint}/admin/currencies`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name_es', label: 'Nombre' },
      { key: 'symbol', label: 'Simbolo' },
      { key: 'decimal_places', label: 'Decimales' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'exchange_rates',
    label: 'Tasas de Cambio',
    description: 'Paridades entre monedas.',
    area: 'Geografia y Moneda',
    appFunction: 'Mantiene paridades para calculos multi-moneda.',
    endpoint: '/admin/exchange-rates',
    endpointLabel: `${baseEndpoint}/admin/exchange-rates`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: false,
    columns: [
      { key: 'from_currency', label: 'Desde' },
      { key: 'to_currency', label: 'Hacia' },
      { key: 'rate', label: 'Tasa' },
      { key: 'source', label: 'Fuente' },
      { key: 'effective_date', label: 'Fecha' },
    ],
  },
  {
    key: 'company_types',
    label: 'Tipos de Empresa',
    description: 'Clasificacion de empresa.',
    area: 'Implementadas',
    appFunction: 'Clasifica tipo general de empresa.',
    endpoint: '/admin/lookups/company_types',
    endpointLabel: `${baseEndpoint}/admin/lookups/company_types`,
    supportsCreate: true,
    supportsEdit: true,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'verification_statuses',
    label: 'Estados de Verificacion',
    description: 'Estados posibles de verificacion.',
    area: 'Implementadas',
    appFunction: 'Controla estados del flujo de verificacion.',
    endpoint: '/admin/lookups/verification_statuses',
    endpointLabel: `${baseEndpoint}/admin/lookups/verification_statuses`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: false,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
    ],
  },
  {
    key: 'payment_terms',
    label: 'Terminos de Pago',
    description: 'Condiciones de pago de operaciones.',
    area: 'Implementadas',
    appFunction: 'Define terminos/condiciones de pago en operaciones.',
    endpoint: '/admin/lookups/payment_terms',
    endpointLabel: `${baseEndpoint}/admin/lookups/payment_terms`,
    supportsCreate: false,
    supportsEdit: false,
    supportsStatus: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'label', label: 'Label' },
      { key: 'is_active', label: 'Status', type: 'status' },
    ],
  },
];

export const LOOKUP_TABLES_BY_KEY = LOOKUP_TABLES.reduce((acc, table) => {
  acc[table.key] = table;
  return acc;
}, {});

export const DEFAULT_LOOKUP_TABLE_KEY = LOOKUP_TABLES[0].key;
